--------------------------------------------------------
--  파일이 생성됨 - 화요일-6월-22-2021   
--------------------------------------------------------
DROP TABLE "JSPID"."BOOK_RANK";
--------------------------------------------------------
--  DDL for Table BOOK_RANK
--------------------------------------------------------

  CREATE TABLE "JSPID"."BOOK_RANK" 
   (	"RANKNO" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JSPID.BOOK_RANK
SET DEFINE OFF;
Insert into JSPID.BOOK_RANK (RANKNO,NAME) values (3,'관리자');
Insert into JSPID.BOOK_RANK (RANKNO,NAME) values (2,'일반사용자');
Insert into JSPID.BOOK_RANK (RANKNO,NAME) values (1,'방문자');
--------------------------------------------------------
--  DDL for Index BOOK_RANK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JSPID"."BOOK_RANK_PK" ON "JSPID"."BOOK_RANK" ("RANKNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOOK_RANK
--------------------------------------------------------

  ALTER TABLE "JSPID"."BOOK_RANK" MODIFY ("RANKNO" NOT NULL ENABLE);
  ALTER TABLE "JSPID"."BOOK_RANK" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "JSPID"."BOOK_RANK" ADD CONSTRAINT "BOOK_RANK_PK" PRIMARY KEY ("RANKNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
