--------------------------------------------------------
--  파일이 생성됨 - 화요일-6월-22-2021   
--------------------------------------------------------
DROP TABLE "JSPID"."BOOKSTORE";
--------------------------------------------------------
--  DDL for Table BOOKSTORE
--------------------------------------------------------

  CREATE TABLE "JSPID"."BOOKSTORE" 
   (	"NO" NUMBER, 
	"TITLE" VARCHAR2(50 BYTE), 
	"AUTHOR" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER DEFAULT 0, 
	"PUBLISHER" VARCHAR2(30 BYTE), 
	"PUB_DATE" DATE DEFAULT sysdate, 
	"RENTAL" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "JSPID"."BOOKSTORE"."RENTAL" IS '유저no
';
REM INSERTING into JSPID.BOOKSTORE
SET DEFINE OFF;
Insert into JSPID.BOOKSTORE (NO,TITLE,AUTHOR,PRICE,PUBLISHER,PUB_DATE,RENTAL) values (1,'백설공주','김단비',4000,'아이나라',to_date('21/06/22','RR/MM/DD'),0);
Insert into JSPID.BOOKSTORE (NO,TITLE,AUTHOR,PRICE,PUBLISHER,PUB_DATE,RENTAL) values (2,'비밀','강설화',7000,'트렌서',to_date('21/06/22','RR/MM/DD'),0);
Insert into JSPID.BOOKSTORE (NO,TITLE,AUTHOR,PRICE,PUBLISHER,PUB_DATE,RENTAL) values (3,'우주의 신비','김충렬',7000,'망원경',to_date('21/06/22','RR/MM/DD'),0);
Insert into JSPID.BOOKSTORE (NO,TITLE,AUTHOR,PRICE,PUBLISHER,PUB_DATE,RENTAL) values (4,'단군신화','최철',4000,'나무나라',to_date('21/06/22','RR/MM/DD'),0);
Insert into JSPID.BOOKSTORE (NO,TITLE,AUTHOR,PRICE,PUBLISHER,PUB_DATE,RENTAL) values (5,'코딩의 정석','우정진',9000,'유투버',to_date('21/06/22','RR/MM/DD'),0);
Insert into JSPID.BOOKSTORE (NO,TITLE,AUTHOR,PRICE,PUBLISHER,PUB_DATE,RENTAL) values (6,'소나기','오설백',10000,'감자꽃',to_date('21/06/22','RR/MM/DD'),0);
--------------------------------------------------------
--  DDL for Index LIBRARY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JSPID"."LIBRARY_PK" ON "JSPID"."BOOKSTORE" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOOKSTORE
--------------------------------------------------------

  ALTER TABLE "JSPID"."BOOKSTORE" MODIFY ("NO" NOT NULL ENABLE);
  ALTER TABLE "JSPID"."BOOKSTORE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "JSPID"."BOOKSTORE" MODIFY ("AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "JSPID"."BOOKSTORE" MODIFY ("RENTAL" NOT NULL ENABLE);
  ALTER TABLE "JSPID"."BOOKSTORE" ADD CONSTRAINT "LIBRARY_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
