--------------------------------------------------------
--  파일이 생성됨 - 화요일-6월-22-2021   
--------------------------------------------------------
DROP TABLE "JSPID"."BOOK_USER";
--------------------------------------------------------
--  DDL for Table BOOK_USER
--------------------------------------------------------

  CREATE TABLE "JSPID"."BOOK_USER" 
   (	"NO" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"ID" VARCHAR2(30 BYTE), 
	"PW" VARCHAR2(30 BYTE), 
	"AGE" NUMBER, 
	"GENDER" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"SIGN_UP" DATE DEFAULT SYSDATE, 
	"RANK" NUMBER DEFAULT 0, 
	"RENTAL_CNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JSPID.BOOK_USER
SET DEFINE OFF;
Insert into JSPID.BOOK_USER (NO,NAME,ID,PW,AGE,GENDER,ADDRESS,EMAIL,SIGN_UP,RANK,RENTAL_CNT) values (5,'김은아','eun12','123',22,'여자','서울 은평구',null,to_date('21/06/18','RR/MM/DD'),2,0);
Insert into JSPID.BOOK_USER (NO,NAME,ID,PW,AGE,GENDER,ADDRESS,EMAIL,SIGN_UP,RANK,RENTAL_CNT) values (4,'정동수','jung22','123',17,'남자','서울 마포구',null,to_date('21/06/18','RR/MM/DD'),1,0);
Insert into JSPID.BOOK_USER (NO,NAME,ID,PW,AGE,GENDER,ADDRESS,EMAIL,SIGN_UP,RANK,RENTAL_CNT) values (3,'새초롬','birdoo','123',31,'여자','경기 고양시',null,to_date('21/06/18','RR/MM/DD'),1,0);
Insert into JSPID.BOOK_USER (NO,NAME,ID,PW,AGE,GENDER,ADDRESS,EMAIL,SIGN_UP,RANK,RENTAL_CNT) values (2,'채형길','roadchea','123',27,'남자','충남 아산',null,to_date('21/06/18','RR/MM/DD'),1,0);
Insert into JSPID.BOOK_USER (NO,NAME,ID,PW,AGE,GENDER,ADDRESS,EMAIL,SIGN_UP,RANK,RENTAL_CNT) values (1,'조수아','suaaa','123',34,'여자','강원 횡성',null,to_date('21/06/18','RR/MM/DD'),1,0);
--------------------------------------------------------
--  DDL for Index BOOK_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JSPID"."BOOK_USER_PK" ON "JSPID"."BOOK_USER" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOOK_USER
--------------------------------------------------------

  ALTER TABLE "JSPID"."BOOK_USER" MODIFY ("NO" NOT NULL ENABLE);
  ALTER TABLE "JSPID"."BOOK_USER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "JSPID"."BOOK_USER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "JSPID"."BOOK_USER" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "JSPID"."BOOK_USER" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "JSPID"."BOOK_USER" ADD CONSTRAINT "BOOK_USER_CHK1" CHECK (GENDER in ('남자','여자')) ENABLE;
  ALTER TABLE "JSPID"."BOOK_USER" ADD CONSTRAINT "BOOK_USER_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
